export const rapNames = [
  "Childish Bitcoin",
  "Bhad Dyor",
  "Meme Galz",
  "Swifty Crash",
  "Moody Whale",
  "Zuck Boi",
  "Mutant Bars",
  "Off-Doge",
  "0xPaperhands",
  "Notorious HODL",
  "Bubble Cute",
  "FVCK Wei",
  "MC Libertarian",
  "JPEG Quantum",
  "Degen Gang",
  "Yung Shiba",
  "Papi Shill",
  "Shill.wav",
  "FUD Nasty",
  "Proof of Wei",
  "Yung Ponzi",
  "REKT Ohmie",
  "Wagmi Whale",
  "Lonely Rug",
  "Pop Gox",
  "Wu Tang Meme",
  "Astro Ponzi",
  "Lil Mint",
  "La HODL",
  "Wen Art",
  "Fud Mami",
  "Wagmi Swift",
  "Fiat Silly",
  "Luv Waifu",
  "Dorky Shill",
  "MC Zuck",
  "Yung Fud",
  "Ponzi Moon",
  "REKT Alien",
  "Hans Diamond",
  "Quantum Moon",
  "gm gal",
  "MC JPEG",
  "Bored Degen",
  "Lonely Shiba",
  "Dreamy GM",
  "DYOR Bags",
  "Shill Chill",
  "Proof of Ape",
  "Major FOMO",
  "Wen REKT",
  "Moody Bear",
  "Degen Wei",
  "Meme Ape",
  "Lazy Cardano",
  "Waifuverse",
  "Mutant Waifu",
  "Childish Wagmi",
  "0xFUD",
  "REKT God",
  "Dat Buterin",
  "Lonely Lambo",
  "Pumpa Bag",
  "FVCK Meta",
  "Lil Dip",
  "Big Wagmi",
  "gm degen",
  "Meme Wav",
  "Dreamy Hash",
  "Crypto Papi",
  "Lil FOMO",
  "50 Sats",
  "Wen Cardano",
  "Lil Bull",
  "Lonely Whale",
  "Ugly Meme",
  "Moody Merkle",
  "Don Tron",
  "Pepe Pig",
  "La Paperhands",
  "Lil DAO",
  "Bhad Mint",
  "Wu Tang FOMO",
  "Yung DAO",
  "Childish Ponzino",
  "Rug Gang",
  "FVCK boi",
  "Poppa Sats",
  "Gm-Unit",
  "Moon Gal",
  "Poppa Airdrop",
  "Lil Ponzi",
  "Moody DYOR",
  "FVCK Meme",
  "Nifty Jpeg",
  "Big REKT",
  "Gwei-Z",
  "Vitalik MC",
  "Bear Boi",
  "Lil Memecoin"
]