export const rapNames = [
  "Childish Bitcoin",
  "Bhad Dyor",
  "Meme Galz",
  "Swifty Crash",
  "Moody Whale",
  "Zuck Boi",
  "Mutant Bars",
  "Off-Doge",
  "0xPaperhands",
  "Notorious HODL",
  "Bubble Cute",
  "FVCK Wei",
  "MC Libertarian",
  "JPEG Quantum ",
  "Degen Gang",
  "Yung Shiba",
  "Papi Shill",
  "Shill.wav",
  "FUD Nasty",
  "Proof of Wei",
  "Yung Ponzi",
  "REKT Ohmie",
  "Wagmi Whale",
  "Lonely Rug",
  "Pop Gox",
  "Wu Tang Meme",
  "Astro Ponzi",
  "Lil Mint",
  "La HODL",
  "Wen Art",
  "Fud Mami",
  "Wagmi Swift",
  "Fiat Silly",
  "Luv Waifu",
  "Dorky Shill",
  "MC Zuck",
  "Yung Fud",
  "Ponzi Moon",
  "REKT Alien",
  "Hans Diamond",
  "Quantum Moon",
  "gm gal",
  "MC JPEG",
  "Bored Degen",
  "Lonely Shiba",
  "Dreamy GM",
  "DYOR Bags",
  "Shill Chill",
  "Proof of Ape",
  "Major FOMO",
  "Wen REKT",
  "Moody Bear",
  "Degen Wei",
  "Meme Ape",
  "Lazy Cardano",
  "Waifuverse",
  "Mutant Waifu",
  "Childish Wagmi",
  "0xFUD",
  "REKT God",
  "Dat Buterin",
  "Lonely Lambo",
  "Pumpa Bag",
  "FVCK Meta",
  "Lil Dip",
  "Big Wagmi",
  "gm degen",
  "Meme Wav",
  "Dreamy Hash",
  "Crypto Papi",
  "Lil FOMO",
  "50 Sats",
  "Wen Cardano",
  "Lil Bull",
  "Lonely Whale",
  "Ugly Meme",
  "Moody Merkle",
  "Don Tron",
  "Pepe Pig",
  "La Paperhands",
  "Lil DAO",
  "Bhad Mint",
  "Wu Tang FOMO",
  "Yung DAO",
  "Childish Ponzino",
  "Rug Gang",
  "FVCK boi",
  "Poppa Sats",
  "Gm-Unit",
  "Moon Gal",
  "Poppa Airdrop",
  "Lil Ponzi",
  "Moody DYOR",
  "FVCK Meme",
  "Nifty Jpeg",
  "Big REKT",
  "Gwei-Z",
  "Vitalik MC",
  "Bear Boi",
  "Lil Memecoin",
  "FOMO Nasty",
  "0xRug",
  "LL Cool Stake",
  "Cardano B",
  "Smart Node Boys",
  "Freaky NFT Boss",
  "Sick Gox Boys",
  "Mining Altcoin Kids",
  "Silly Gox Gals",
  "Bored Citadel Bois",
  "Calm Memecoin Gals",
  "Big Liquid ",
  "Bhad APY Gang",
  "Ol' Craig Wright ",
  "Freaky Laser Club",
  "Crypto Hash Twins",
  "0xMerkle ",
  "Bhad Solana Gals",
  "Wu Tang Bubble ",
  "Da Mint Starr",
  "Doge Gang Goonz",
  "Hood Shiba ",
  "Run The Metaverse ",
  "Freaky Rug ",
  "Hood Flip ",
  "Degen Gal ",
  "Dreamy Flip Bois",
  "The Chain Gang",
  "A Tribe Called Punks",
  "Zombie Dip Club",
  "Yung Apes",
  "Freaky Node Boys",
  "Lonely gm ",
  "The Shill Boss",
  "La Wav Gang",
  "Happy Hash ",
  "Gold Ledger Gang",
  "Lil Dip Gals",
  "Space shiba Boys",
  "Bad Jpeg Club",
  "Degen Waifu Robots",
  "Odd Jpeg Bois",
  "Baby Anarchist ",
  "Nasty Shiba Bois",
  "A Tribe Called Tokenomics",
  "Mac Fud",
  "Silly Elon ",
  "Schoolboy Tor",
  "Mad REKT ",
  "Hood Hash Squad",
  "Sybil Gang",
  "3D Waifu Squad",
  "Schoolboy Crypto ",
  "Yung World Punks",
  "Space Rug ",
  "Diamond Meme ",
  "DAO-Z",
  "Lil Memecoin Boss",
  "3D Shiba The God",
  "Bhad Memecoin ",
  "Run The Shills",
  "Quantum DAO Bois",
  "Moon Mobb",
  "La Nakamoto ",
  "Block Apes Gang",
  "A Tribe Called Wagmi ",
  "Wild Jpeg ",
  "Degen Crash ",
  "Freaky Shill ",
  "Hot Jpeg Gals",
  "Freaky Roadmap ",
  "Mad Winklevoss Squad",
  "Yung Cardano Bois",
  "Meta Jpeg",
  "Kid DYOR ",
  "Yung Zora Punks",
  "0xMoon ",
  "Mint Street",
  "Wagmi Unit",
  "Lambo Fidenza",
  "Whale Goonz",
  "Ponzi Bois",
  "Fluf Kids",
  "NFT The God",
  "Airdrop Boss",
  "Bubble C",
  "Ohmie Gang",
  "FUD Starr",
  "Waifu Starr",
  "HODL Club",
  "Diamond Hands Goonz",
  "Bubble Boss",
  "Jpeg Crazy",
  "Rug Twins",
  "Liberty Ape",
  "Jpeg The God",
  "Waifu Twins",
  "DAO Bois",
  "REKT Unit",
  "Rug Pull Boys",
  "Doge Gal",
  "Cheugy Goonz",
  "Wagmi Kids",
  "Punk Wavs",
  "Meme B ",
  "Binance Squad",
  "REKT Starr",
  "Moon Gang",
  "Dip Unit",
  "Fiat Gals",
  "APY Ape",
  "Trustless Gang",
  "HODL Gals",
  "Rug Pull Unit",
  "Diamond Hands Punk",
  "Zora Gals",
  "Furry Musk",
  "Wifi Baby",
  "Witty Meme",
  "A Tribe Called GM",
  "Lil Axie Baby",
  "FVCK Shill"
]